version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    container_name: keycloak-sc
    env_file:
      - ./.env
    ports:
      - '8027:8080'
    command: start-dev
    networks:
      - nlcntt-network
    restart: unless-stopped
    volumes:
      - keycloak:/opt/keycloak/data/
    depends_on:
      - db
  db:
    image: postgres # use latest official postgres version
    container_name: postgres-db
    env_file:
      - ./.env
    ports:
      - '$POSTGRES_HOST_PORT:$POSTGRES_CONTAIER_PORT'
    networks:
      - nlcntt-network
    restart: always
    volumes:
      - db:$PGDATA
  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-be
    env_file:
      - ./.env
    ports:
      - '$SERVER_HOST_PORT:$SERVER_CONTAINER_PORT'
    volumes:
      - './:/src'
      - 'server:/opt/jboss/wildfly/standalone/log'
      - './keys:/opt/jboss/wildfly/standalone/configuration/keys'
    networks:
      - nlcntt-network
networks:
  nlcntt-network:
    name: nlcntt-network
    attachable: true
    driver: bridge
volumes:
  keycloak:
  db:
  server:
