version: "3.8"
services:
  # keycloak:
  #   image: quay.io/keycloak/keycloak:18.0.2
  #   container_name: keycloak_identity
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "8027:8080"
  #   command: start-dev
  #   environment:
  #     - DB_ADDR=${KEYCLOAK_DATABASE_HOST}
  #     - DB_VENDOR=${KEYCLOAK_DATABASE_VENDOR}
  #     - DB_USER=${POSTGRES_USER}
  #     - DB_PASSWORD=${POSTGRES_PASSWORD}
  #     - DB_DATABASE=${POSTGRES_DB}
  #     # - DB_PORT=${POSTGRES_LOCAL_PORT}
  #     # - DB_SCHEMA=public
  #     - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
  #     - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
  #   networks:
  #     - mynet
  #   restart: unless-stopped
  #   depends_on:
  #     - db
  db:
    image: postgres # use latest official postgres version
    container_name: postgres-db
    env_file:
      - ./.env # configure postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /var/lib/postgresql/data
    # hostname: postgres
    ports:
      - '5432:5432'
    # expose:
    #   - 5432
    networks:
      - mynet
    restart: always
    volumes:
      - db:/var/lib/postgresql/data # persist data even if container shuts down

  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '8080:8080'
    volumes:
      - './:/src'
      - 'server:/opt/jboss/wildfly/standalone/log'
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
volumes:
  db: # named volumes can be managed easier using docker-compose
  server:
